name    'vladistan/puppet-justhub'
version '0.1.0'
source ''
author 'Vlad Korolev <vlad@dblfuzzr.com>'
license 'Apache License Version 2.0'
summary 'A Puppet Module that install justhub repo'
description 'A Puppet Module that install justhub repo'
project_page 'https://github.com/vladistan/puppet-justhub'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
